name: "match-tag-to-package-version"
description: "Makes sure that git tag and version in package.json match"
runs:
  using: "node12"
  main: "src/index.js"
branding:
  icon: "tag"
  color: "yellow"
outputs:
  tag:
    description: The tag with `refs/tags/` stripped off.
  version:
    description: The version string exactly as it appears in package.json
