name: "match-tag-to-package-version"
description: "Makes sure that git tag and version in package.json match"
runs:
  using: "node12"
  main: "dist/main.js"
branding:
  icon: "tag"
  color: "yellow"
outputs:
  tag:
    description: The tag with `refs/tags/` stripped off.
  version:
    description: The version string exactly as it appears in package.json
inputs:
  tag_prefix:
    default: ''
    description: Allow the tag to differ from the package version by this prefix
    required: false