name: "match-tag-to-package-version"
description: "Makes sure that git tag and version in package.json match"
runs:
  using: "node12"
  main: "src/index.js"
branding:
  icon: "tag"
  color: "yellow"
outputs:
  packageVersion:
    description: The version number from package.json
  tag:
    description: The tag, complete with any prefix
  tagVersion:
    description: What's left of the tag after trimming the prefix
